name: med-pain-sig
channels:
  - ejolly
  - conda-forge
  - defaults
dependencies:
  - nilearn==0.10.4
  - notebook==7.1.3
  - pandas==2.2.2
  - pymer4==0.8.2
  - seaborn==0.13.2
  - statsmodels==0.14.2
  - pip==24.0
  - pip:
    - templateflow==24.2.0